####
#Method Request-URI HTTP-Version
#Header-field: Header-value
#
#Request-Body

### Basic Health Check
GET http://{{host}}:{{port}}/health

### Basic Health Check
GET http://{{host}}:{{port}}/info

### Swagger exposed
GET http://{{host}}:{{port}}/swagger-ui

### Rapidoc exposed
GET http://{{host}}:{{port}}/rapidoc

### Redoc exposed
GET http://{{host}}:{{port}}/redoc


