micronaut:
  application:
    name: horae
  metrics:
    export:
      datadog:
        enabled: true
        apiKey: ${DATADOG_APIKEY:bogus_key}
        step: PT1M
    enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
netty:
  default:
    allocator:
      max-order: 3

endpoints:
  info:
    enabled: true
    sensitive: false

neo4j:
  uri: bolt://${NEO4J_HOST:localhost}
